#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon May  7 10:29:49 2018

@author: Tom
"""

import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt


def minicircle_reader(file):
    lines = []
    for line in open(file):
        line=line.replace("-"," -")
        list=line.split()
        lines.append(list)
    return lines
    
def atom_coords(lines):
    x = []
    y = []
    z = []
    for line in lines:
        x.append(float(line[6]))
        y.append(float(line[7]))
        z.append(float(line[8]))
    return [x, y, z]

def minicircle2coords(file):
    lines = minicircle_reader(file)
    [x,y,z] = atom_coords(lines)
    return [x, y, z]

def plot_minicircle(file):
    mpl.rcParams['legend.fontsize'] = 10
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    [x,y,z] = minicircle2coords(file)
    ax.plot(x, y, z, label='DNA Minicircle')
    ax.legend()
    plt.show()



    
    